### ISSUE TITLE
Some Build Errors Encountered

### ISSUE THREAD

**Issue by x0v0l** [m0ck1ng/mock#2]
Hi! Sorry to bother. I like your paper but am experiencing several problems while trying to compile MOCK:

1. **Using Rust Version Above 1.70**  
   When using a Rust version higher than 1.70, executing `cargo build --release` results in errors. The error occurs in the file `syz_wrapper/src/repro.rs` between lines 178-193, with the following messages:
   ```
   error: no rules expected the token `:`
   and
   no rules expected this token in macro call (there's an arrow pointing to the right parenthesis in line 193)
   ```
   Additionally, there is a note indicating:
   ```
   note: this error originates in the macro `json_internal_owned` which comes from the expansion of the macro `json`
   ```

2. **Using Rust Version Below 1.70**  
   When using a Rust version lower than 1.70, some toolchains cannot be compiled. For example, the following error occurs:
   ```
   error: package `tokio-util v0.7.12` cannot be built because it requires rustc 1.70 or newer, while the currently active rustc version is 1.65.0
   ```

3. **Linking Errors with Rust 1.70**  
   When compiling with Rust 1.70, there seems to be a linking error at the final stage. The error messages are as follows:
   ```
   note: /usr/bin/ld: warning: libgomp-52f2fd74.so.1, needed by /xx/mock/target/release/build/torch-sys-7524fed8452c3292/out/libtorch/libtorch/lib/libtorch_cpu.so
   and
   mock/target/release/build/torch-sys-7524fed8452c3292/out/libtorch/libtorch/lib/libtorch_cpu.so: undefined reference to `powf@GLIBC_2.27',
   `log2f@GLIBC_2.27', `expf@GLIBC_2.27', `exp2f@GLIBC_2.27', `logf@GLIBC_2.27'
   ```
   Even after specifying glibc-2.27 and copying `libgomp.so.1` to `libgomp-52f2fd74.so.1`, the errors persist.

I would appreciate any assistance or guidance on resolving these issues. Thank you!

**Comment by x0v0l** [comment]
Update:
The errors with rust-1.70 occur on a cpu server. Later I changed to a gpu server and repeated the same operations, and the compiling process succeeded. So maybe it's my own environment problem or a mock-on-cpu-machine problem.

**Comment by q1uTr5th** [comment]
> Update: The errors with rust-1.70 occur on a cpu server. Later I changed to a gpu server and repeated the same operations, and the compiling process succeeded. So maybe it's my own environment problem or a mock-on-cpu-machine problem.

Hi, same build errors, on Ubuntu 20.04 and Rust version 1.81.0.
```
error: no rules expected the token `:`
and
no rules expected this token in macro call (there's an arrow pointing to the right parenthesis in line 193)
```

What are the operating systems for cpu servers and gpu servers? Also the Rust version 1.70? Thank you!

**Comment by x0v0l** [comment]
> > Update: The errors with rust-1.70 occur on a cpu server. Later I changed to a gpu server and repeated the same operations, and the compiling process succeeded. So maybe it's my own environment problem or a mock-on-cpu-machine problem.
> 
> Hi, same build errors, on Ubuntu 20.04 and Rust version 1.81.0.
> 
> ```
> error: no rules expected the token `:`
> and
> no rules expected this token in macro call (there's an arrow pointing to the right parenthesis in line 193)
> ```
> 
> What are the operating systems for cpu servers and gpu servers? Also the Rust version 1.70? Thank you!

I succeeded to compile on Ubuntu 20.04 with Rust-1.70, and with cuda 10.1

**Comment by m0ck1ng** [comment]
Thanks for reaching out. I used the rust toolchain with version rustc 1.57.0 (f1edd0429 2021-11-29) and it worked well on my cpu-only machine. The problem can be due to some environmental dependencies related to `tch-rs` or `libtorch`.

**Comment by x0v0l** [comment]
Thanks a lot! Problems are probably because of my env dependencies. So this issue should be closed.
