### ISSUE TITLE
error: no rules expected the token `:`    --> syz_wrapper/src/repro.rs:178:16

### ISSUE THREAD

**Issue by zhanglchun** [m0ck1ng/mock#3]
warning: methods `overflowing_add` and `overflowing_neg` are never used
   --> healer_core/src/mutation/buffer.rs:416:8
    |
412 | trait Number: Sized {
    |       ------ methods in this trait
...
416 |     fn overflowing_add(self, rhs: Self) -> (Self, bool);
    |        ^^^^^^^^^^^^^^^
417 |     fn overflowing_neg(self) -> (Self, bool);
    |        ^^^^^^^^^^^^^^^
    |
    = note: `#[warn(dead_code)]` on by default

error: no rules expected the token `:`
   --> syz_wrapper/src/repro.rs:178:16
    |
178 |       let conf = json!({
    |  ________________^
179 | |         "target": &conf.target,
180 | |         "http": "127.0.0.1:65534",
181 | |         "workdir": &conf.work_dir,
...   |
192 | |         }
193 | |     });
    | |______^ no rules expected this token in macro call
    |
note: while trying to match `=>`
   --> /home/zl/.cargo/registry/src/index.crates.io-6f17d22bba15001f/simd-json-0.4.15/src/macros.rs:296:46
    |
296 |     (@object @count [@entries $(($value:expr => $($key:tt)+))*]) => {
    |                                              ^^
    = note: this error originates in the macro `json_internal_owned` which comes from the expansion of the macro `json` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `syz_wrapper` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
warning: `healer_core` (lib) generated 1 warning

**Comment by q1uTr5th** [comment]
@zhanglchun same error, but solved by refering https://github.com/m0ck1ng/mock/issues/2#issue-2543059748. I succeed on my cpu-only-machine, ubuntu 20.04, rust version 1.70.0. The error is translated to a warning by changing rust to 1.70.0.

**Comment by m0ck1ng** [comment]
I think the issue has been addressed and I'll close it.
If you have more questions, feel free to reach out.
